### ISSUE TITLE
KeyError: 'CMCD is not in the models registry'

### ISSUE THREAD

**Issue by Submarinee** [CAU-HE/CMCDNet#3]
2023-07-31 10:34:19,264 - mmseg - INFO - Set random seed to 1861047, deterministic: False
Traceback (most recent call last):
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmseg/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zw21/anaconda3/envs/cmcdnet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CMCD is not in the models registry'

想问一下这个怎么解决，在运行python tools/train.py my_scripts/water_change/opt_sar_cmcd_r50-effb2_30e.py时报错CMCD is not in the models registry，我的代码都是没有改的

**Comment by Submarinee** [comment]
i found that the mmseg  directory in your repo can be installed.
